{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "apps.serviceAccountName" . }}
  labels:
{{ include "apps.labels" . | indent 4 }}
{{- end -}}
